name: Build and Deploy to Surfer

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js v18
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install Node dependencies
        run: npm install

      - name: Setup Github API variables
        run: |
          echo 'REACT_APP_GITHUB_URL=https://api.github-com' > .env.sample \
          echo 'REACT_APP_GITHUB_TOKEN=' >> .env.sample \
          echo ${{ secrets.API_TOKEN }} >> .env.sample
          mv .env.sample .env

      - name: Cat file
        run: cat .env

      - name: Build React app
        run: npm run build --if-present

      - name: Upload build to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: react_build
          path: build/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build from artifacts
        uses: actions/download-artifact@v3
        with:
          name: react_build

      - name: Display files
        run: ls -R