name: Build and Deploy to Surfer

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build the application
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js v18
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install Node dependencies
        run: npm install

      - name: Setup ENV file
        uses: DamianReeves/write-file-action@master
        with:
          path: .env.sample
          contents: |
            REACT_APP_GITHUB_URL=https://api.github.com
            REACT_APP_GITHUB_TOKEN=${{ secrets.API_TOKEN }}
          write-mode: overwrite

      - name: Build React app
        run: npm run build --if-present

      - name: Upload build to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: react_build
          path: build/

  deploy:
    name: Deploy to Surfer
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build from artifacts
        uses: actions/download-artifact@v3
        with:
          name: react_build
          path: build

      - name: Install Surfer CLI
        run: npm -g install cloudron-surfer

      - name: Copy build to Surfer
        env:
          SURFER_API_TOKEN: ${{ secrets.SURFER_TOKEN }}
        run: |
          surfer put --token "$env:SURFER_API_TOKEN" --server github-finder.santoscloud.pt build/. /