name: Build and Deploy to Surfer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v18
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm run build --if-present
